// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.passulo.token

/** @param id
  *   identifier for this token only
  */
@SerialVersionUID(0L)
final case class Token(
    id: _root_.scala.Predef.String = "",
    firstName: _root_.scala.Predef.String = "",
    middleName: _root_.scala.Predef.String = "",
    lastName: _root_.scala.Predef.String = "",
    gender: com.passulo.token.Token.Gender = com.passulo.token.Token.Gender.undefined,
    number: _root_.scala.Predef.String = "",
    status: _root_.scala.Predef.String = "",
    company: _root_.scala.Predef.String = "",
    email: _root_.scala.Predef.String = "",
    telephone: _root_.scala.Predef.String = "",
    association: _root_.scala.Predef.String = "",
    validUntil: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    memberSince: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Token] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = id
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = firstName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = middleName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = lastName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = gender.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(5, __value)
        }
      };
      
      {
        val __value = number
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = status
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      
      {
        val __value = company
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, __value)
        }
      };
      
      {
        val __value = email
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, __value)
        }
      };
      
      {
        val __value = telephone
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(10, __value)
        }
      };
      
      {
        val __value = association
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(11, __value)
        }
      };
      if (validUntil.isDefined) {
        val __value = validUntil.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (memberSince.isDefined) {
        val __value = memberSince.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = id
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = firstName
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = middleName
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = lastName
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = gender.value
        if (__v != 0) {
          _output__.writeEnum(5, __v)
        }
      };
      {
        val __v = number
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = status
        if (!__v.isEmpty) {
          _output__.writeString(7, __v)
        }
      };
      {
        val __v = company
        if (!__v.isEmpty) {
          _output__.writeString(8, __v)
        }
      };
      {
        val __v = email
        if (!__v.isEmpty) {
          _output__.writeString(9, __v)
        }
      };
      {
        val __v = telephone
        if (!__v.isEmpty) {
          _output__.writeString(10, __v)
        }
      };
      {
        val __v = association
        if (!__v.isEmpty) {
          _output__.writeString(11, __v)
        }
      };
      validUntil.foreach { __v =>
        val __m = __v
        _output__.writeTag(12, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      memberSince.foreach { __v =>
        val __m = __v
        _output__.writeTag(13, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withId(__v: _root_.scala.Predef.String): Token = copy(id = __v)
    def withFirstName(__v: _root_.scala.Predef.String): Token = copy(firstName = __v)
    def withMiddleName(__v: _root_.scala.Predef.String): Token = copy(middleName = __v)
    def withLastName(__v: _root_.scala.Predef.String): Token = copy(lastName = __v)
    def withGender(__v: com.passulo.token.Token.Gender): Token = copy(gender = __v)
    def withNumber(__v: _root_.scala.Predef.String): Token = copy(number = __v)
    def withStatus(__v: _root_.scala.Predef.String): Token = copy(status = __v)
    def withCompany(__v: _root_.scala.Predef.String): Token = copy(company = __v)
    def withEmail(__v: _root_.scala.Predef.String): Token = copy(email = __v)
    def withTelephone(__v: _root_.scala.Predef.String): Token = copy(telephone = __v)
    def withAssociation(__v: _root_.scala.Predef.String): Token = copy(association = __v)
    def getValidUntil: com.google.protobuf.timestamp.Timestamp = validUntil.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearValidUntil: Token = copy(validUntil = _root_.scala.None)
    def withValidUntil(__v: com.google.protobuf.timestamp.Timestamp): Token = copy(validUntil = Option(__v))
    def getMemberSince: com.google.protobuf.timestamp.Timestamp = memberSince.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearMemberSince: Token = copy(memberSince = _root_.scala.None)
    def withMemberSince(__v: com.google.protobuf.timestamp.Timestamp): Token = copy(memberSince = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = id
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = firstName
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = middleName
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = lastName
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = gender.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 6 => {
          val __t = number
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = status
          if (__t != "") __t else null
        }
        case 8 => {
          val __t = company
          if (__t != "") __t else null
        }
        case 9 => {
          val __t = email
          if (__t != "") __t else null
        }
        case 10 => {
          val __t = telephone
          if (__t != "") __t else null
        }
        case 11 => {
          val __t = association
          if (__t != "") __t else null
        }
        case 12 => validUntil.orNull
        case 13 => memberSince.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(id)
        case 2 => _root_.scalapb.descriptors.PString(firstName)
        case 3 => _root_.scalapb.descriptors.PString(middleName)
        case 4 => _root_.scalapb.descriptors.PString(lastName)
        case 5 => _root_.scalapb.descriptors.PEnum(gender.scalaValueDescriptor)
        case 6 => _root_.scalapb.descriptors.PString(number)
        case 7 => _root_.scalapb.descriptors.PString(status)
        case 8 => _root_.scalapb.descriptors.PString(company)
        case 9 => _root_.scalapb.descriptors.PString(email)
        case 10 => _root_.scalapb.descriptors.PString(telephone)
        case 11 => _root_.scalapb.descriptors.PString(association)
        case 12 => validUntil.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 13 => memberSince.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.passulo.token.Token.type = com.passulo.token.Token
    // @@protoc_insertion_point(GeneratedMessage[com.passulo.v1.Token])
}

object Token extends scalapb.GeneratedMessageCompanion[com.passulo.token.Token] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.passulo.token.Token] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.passulo.token.Token = {
    var __id: _root_.scala.Predef.String = ""
    var __firstName: _root_.scala.Predef.String = ""
    var __middleName: _root_.scala.Predef.String = ""
    var __lastName: _root_.scala.Predef.String = ""
    var __gender: com.passulo.token.Token.Gender = com.passulo.token.Token.Gender.undefined
    var __number: _root_.scala.Predef.String = ""
    var __status: _root_.scala.Predef.String = ""
    var __company: _root_.scala.Predef.String = ""
    var __email: _root_.scala.Predef.String = ""
    var __telephone: _root_.scala.Predef.String = ""
    var __association: _root_.scala.Predef.String = ""
    var __validUntil: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var __memberSince: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __id = _input__.readStringRequireUtf8()
        case 18 =>
          __firstName = _input__.readStringRequireUtf8()
        case 26 =>
          __middleName = _input__.readStringRequireUtf8()
        case 34 =>
          __lastName = _input__.readStringRequireUtf8()
        case 40 =>
          __gender = com.passulo.token.Token.Gender.fromValue(_input__.readEnum())
        case 50 =>
          __number = _input__.readStringRequireUtf8()
        case 58 =>
          __status = _input__.readStringRequireUtf8()
        case 66 =>
          __company = _input__.readStringRequireUtf8()
        case 74 =>
          __email = _input__.readStringRequireUtf8()
        case 82 =>
          __telephone = _input__.readStringRequireUtf8()
        case 90 =>
          __association = _input__.readStringRequireUtf8()
        case 98 =>
          __validUntil = Option(__validUntil.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 106 =>
          __memberSince = Option(__memberSince.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.passulo.token.Token(
        id = __id,
        firstName = __firstName,
        middleName = __middleName,
        lastName = __lastName,
        gender = __gender,
        number = __number,
        status = __status,
        company = __company,
        email = __email,
        telephone = __telephone,
        association = __association,
        validUntil = __validUntil,
        memberSince = __memberSince,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.passulo.token.Token] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.passulo.token.Token(
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        firstName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        middleName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        lastName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        gender = com.passulo.token.Token.Gender.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(com.passulo.token.Token.Gender.undefined.scalaValueDescriptor).number),
        number = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        status = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        company = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        email = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        telephone = __fieldsMap.get(scalaDescriptor.findFieldByNumber(10).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        association = __fieldsMap.get(scalaDescriptor.findFieldByNumber(11).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        validUntil = __fieldsMap.get(scalaDescriptor.findFieldByNumber(12).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        memberSince = __fieldsMap.get(scalaDescriptor.findFieldByNumber(13).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TokenProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TokenProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 12 => __out = com.google.protobuf.timestamp.Timestamp
      case 13 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 5 => com.passulo.token.Token.Gender
    }
  }
  lazy val defaultInstance = com.passulo.token.Token(
    id = "",
    firstName = "",
    middleName = "",
    lastName = "",
    gender = com.passulo.token.Token.Gender.undefined,
    number = "",
    status = "",
    company = "",
    email = "",
    telephone = "",
    association = "",
    validUntil = _root_.scala.None,
    memberSince = _root_.scala.None
  )
  sealed abstract class Gender(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
    type EnumType = Gender
    def isundefined: _root_.scala.Boolean = false
    def isfemale: _root_.scala.Boolean = false
    def ismale: _root_.scala.Boolean = false
    def isdiverse: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[Gender] = com.passulo.token.Token.Gender
    final def asRecognized: _root_.scala.Option[com.passulo.token.Token.Gender.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.passulo.token.Token.Gender.Recognized])
  }
  
  object Gender extends _root_.scalapb.GeneratedEnumCompanion[Gender] {
    sealed trait Recognized extends Gender
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Gender] = this
    
    @SerialVersionUID(0L)
    case object undefined extends Gender(0) with Gender.Recognized {
      val index = 0
      val name = "undefined"
      override def isundefined: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object female extends Gender(1) with Gender.Recognized {
      val index = 1
      val name = "female"
      override def isfemale: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object male extends Gender(2) with Gender.Recognized {
      val index = 2
      val name = "male"
      override def ismale: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object diverse extends Gender(3) with Gender.Recognized {
      val index = 3
      val name = "diverse"
      override def isdiverse: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends Gender(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
    lazy val values = scala.collection.immutable.Seq(undefined, female, male, diverse)
    def fromValue(__value: _root_.scala.Int): Gender = __value match {
      case 0 => undefined
      case 1 => female
      case 2 => male
      case 3 => diverse
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = com.passulo.token.Token.javaDescriptor.getEnumTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = com.passulo.token.Token.scalaDescriptor.enums(0)
  }
  implicit class TokenLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.passulo.token.Token]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.passulo.token.Token](_l) {
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def firstName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.firstName)((c_, f_) => c_.copy(firstName = f_))
    def middleName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.middleName)((c_, f_) => c_.copy(middleName = f_))
    def lastName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.lastName)((c_, f_) => c_.copy(lastName = f_))
    def gender: _root_.scalapb.lenses.Lens[UpperPB, com.passulo.token.Token.Gender] = field(_.gender)((c_, f_) => c_.copy(gender = f_))
    def number: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.number)((c_, f_) => c_.copy(number = f_))
    def status: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.status)((c_, f_) => c_.copy(status = f_))
    def company: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.company)((c_, f_) => c_.copy(company = f_))
    def email: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.email)((c_, f_) => c_.copy(email = f_))
    def telephone: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.telephone)((c_, f_) => c_.copy(telephone = f_))
    def association: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.association)((c_, f_) => c_.copy(association = f_))
    def validUntil: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getValidUntil)((c_, f_) => c_.copy(validUntil = Option(f_)))
    def optionalValidUntil: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.validUntil)((c_, f_) => c_.copy(validUntil = f_))
    def memberSince: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getMemberSince)((c_, f_) => c_.copy(memberSince = Option(f_)))
    def optionalMemberSince: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.memberSince)((c_, f_) => c_.copy(memberSince = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val FIRSTNAME_FIELD_NUMBER = 2
  final val MIDDLENAME_FIELD_NUMBER = 3
  final val LASTNAME_FIELD_NUMBER = 4
  final val GENDER_FIELD_NUMBER = 5
  final val NUMBER_FIELD_NUMBER = 6
  final val STATUS_FIELD_NUMBER = 7
  final val COMPANY_FIELD_NUMBER = 8
  final val EMAIL_FIELD_NUMBER = 9
  final val TELEPHONE_FIELD_NUMBER = 10
  final val ASSOCIATION_FIELD_NUMBER = 11
  final val VALIDUNTIL_FIELD_NUMBER = 12
  final val MEMBERSINCE_FIELD_NUMBER = 13
  def of(
    id: _root_.scala.Predef.String,
    firstName: _root_.scala.Predef.String,
    middleName: _root_.scala.Predef.String,
    lastName: _root_.scala.Predef.String,
    gender: com.passulo.token.Token.Gender,
    number: _root_.scala.Predef.String,
    status: _root_.scala.Predef.String,
    company: _root_.scala.Predef.String,
    email: _root_.scala.Predef.String,
    telephone: _root_.scala.Predef.String,
    association: _root_.scala.Predef.String,
    validUntil: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    memberSince: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]
  ): _root_.com.passulo.token.Token = _root_.com.passulo.token.Token(
    id,
    firstName,
    middleName,
    lastName,
    gender,
    number,
    status,
    company,
    email,
    telephone,
    association,
    validUntil,
    memberSince
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[com.passulo.v1.Token])
}
