// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.passulo.token

object TokenProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.timestamp.TimestampProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      com.passulo.token.Token
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Chdjb20vcGFzc3Vsby90b2tlbi5wcm90bxIOY29tLnBhc3N1bG8udjEaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvd
  G8i8gUKBVRva2VuEhcKAmlkGAEgASgJQgfiPwQSAmlkUgJpZBIsCglmaXJzdE5hbWUYAiABKAlCDuI/CxIJZmlyc3ROYW1lUglma
  XJzdE5hbWUSLwoKbWlkZGxlTmFtZRgDIAEoCUIP4j8MEgptaWRkbGVOYW1lUgptaWRkbGVOYW1lEikKCGxhc3ROYW1lGAQgASgJQ
  g3iPwoSCGxhc3ROYW1lUghsYXN0TmFtZRJBCgZnZW5kZXIYBSABKA4yHC5jb20ucGFzc3Vsby52MS5Ub2tlbi5HZW5kZXJCC+I/C
  BIGZ2VuZGVyUgZnZW5kZXISIwoGbnVtYmVyGAYgASgJQgviPwgSBm51bWJlclIGbnVtYmVyEiMKBnN0YXR1cxgHIAEoCUIL4j8IE
  gZzdGF0dXNSBnN0YXR1cxImCgdjb21wYW55GAggASgJQgziPwkSB2NvbXBhbnlSB2NvbXBhbnkSIAoFZW1haWwYCSABKAlCCuI/B
  xIFZW1haWxSBWVtYWlsEiwKCXRlbGVwaG9uZRgKIAEoCUIO4j8LEgl0ZWxlcGhvbmVSCXRlbGVwaG9uZRIyCgthc3NvY2lhdGlvb
  hgLIAEoCUIQ4j8NEgthc3NvY2lhdGlvblILYXNzb2NpYXRpb24SSwoKdmFsaWRVbnRpbBgMIAEoCzIaLmdvb2dsZS5wcm90b2J1Z
  i5UaW1lc3RhbXBCD+I/DBIKdmFsaWRVbnRpbFIKdmFsaWRVbnRpbBJOCgttZW1iZXJTaW5jZRgNIAEoCzIaLmdvb2dsZS5wcm90b
  2J1Zi5UaW1lc3RhbXBCEOI/DRILbWVtYmVyU2luY2VSC21lbWJlclNpbmNlInAKBkdlbmRlchIdCgl1bmRlZmluZWQQABoO4j8LE
  gl1bmRlZmluZWQSFwoGZmVtYWxlEAEaC+I/CBIGZmVtYWxlEhMKBG1hbGUQAhoJ4j8GEgRtYWxlEhkKB2RpdmVyc2UQAxoM4j8JE
  gdkaXZlcnNlQicKC2NvbS5wYXNzdWxvWhhnaXRodWIuY29tL3Bhc3N1bG8vVG9rZW5iBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      com.google.protobuf.timestamp.TimestampProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}